version: '3.7'

services:
  apinode:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - PORT=${PORT:-3000}
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - POSTGRES_HOST=${DB_HOST:-db}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-clean}
      - POSTGRES_USER=${DB_USER:-clean}
      - POSTGRES_DB=${DB_NAME:-clean}
      - POSTGRES_PORT=${DB_PORT:-5432}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-clean}
      - POSTGRES_USER=${DB_USER:-clean}
      - POSTGRES_DB=${DB_NAME:-clean}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
volumes:
  dbdata:
